version: '3'

services:

  chief_intelligence_officer:
    container_name: chief_intelligence_officer
    image: h0d0user/chief_intelligence_officer:latest
    restart: always
    environment:
      SETTINGS_FILE_FOR_DYNACONF: "/opt/settings.toml"
      VERBOSE: "True"
      ALERTING: "True"
      PLATFORM: "True"
      ENVIRONMENT: "Dev"
#      CHANEL: "TODO"
    networks:
      - chief_intelligence_officer
    volumes:
      - "./settings.toml:/opt/settings.toml"

networks:
  chief_intelligence_officer:

volumes:
  chief_intelligence_officer_volume: