---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cio-daemonset
  labels:
    troubleshooting: "true"
spec:
  selector:
    matchLabels:
      name: cio-daemonset
  template:
    metadata:
      labels:
        name: cio-daemonset
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: cio-daemonset
        image: h0d0user/chief_intelligence_officer:v0.3.5
        env:
        - name: SETTINGS_FILE_FOR_DYNACONF
          value: "/mnt/settings.toml"
        - name: VERBOSE
          value: "True"
        volumeMounts:
        - name: cio-configmaps
          mountPath: /mnt/
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cio-configmaps
        configMap:
          name: cio-configmaps
